pr:
  branches:
    include:
      - dev
  paths:
    exclude:
      - docs/*
      - README.md

trigger:
 branches:
   include:
     - master
 paths:
   exclude:
     - docs/*
     - README.md
     - azure-pipelines-ci.yml
     - azure-pipelines-ci-cd.yml

stages:
- stage: Build_Stage
  displayName: Build Stage
  jobs:
  - job: WebApp
    displayName: Build Web App Job
    pool:
      name: Hosted Windows 2019 with VS2019 
      vmImage: 'windows-2019'
      demands: java
    variables:
      BuildConfiguration: release
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/*.csproj'

    - powershell: |
       Write-Host "Hello World"
       $paths = Get-ChildItem -include *.csproj -Recurse
       foreach($pathobject in $paths) 
       {
           $path = $pathobject.fullname
           $doc = New-Object System.Xml.XmlDocument
           $doc.Load($path)
           $child = $doc.CreateElement("ProjectGuid")
           $child.InnerText = [guid]::NewGuid().ToString().ToUpper()
           $node = $doc.SelectSingleNode("//Project/PropertyGroup")
           $node.AppendChild($child)
           $doc.Save($path)
       }
     